### ISSUE TITLE
tests for new station module

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#53]
* Stores given state
* Retrieve the state
* Update the given state
* Receive a itinerary search query
* Send completed search query to neighbours
* Computes the itinerary correctly
* Does not forward itineraries with potential self-loops
* Does not forward stale queries
* Incorrectly received queries are discarded
* Terminated queries are handed over to query collector
* Consumes rapid input stream of mixed queries
    * number of queries - 1000; 10,000; 1 million

**Comment by prasadtalasila** [comment]
Do put in the credo tool into travis and into the dependencies.

**Comment by SuhasHebbar** [comment]
In a blog post José Valim advices against using mocks in elixir and instead suggests using something similiar to dependency injection for testing.
Would you have any problem with the refactored Station module and its tests be structured keeping the blog post in mind.
http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/

**Comment by SuhasHebbar** [comment]
@VedangW had mentioned an error in https://github.com/prasadtalasila/TransportScheduler/pull/64#issuecomment-354128194 about mocks not being recognised by the GenServer..

It turns out that mox defines mocks private to a process. Since, GenServers run in their own process any mocks defined in the test process will not be visible in the GenServer. To do so one must use ```elixir allow(mock, owner_pid, allowed_pid) ``` or use ```elixir setup :set_mox_global ``` to make the mocks global.

**Comment by prasadtalasila** [comment]
Using global mocks is not a scalable solution. `allow(mock, ...)` seems like a much better solution.

**Comment by prasadtalasila** [comment]
@SuhasHebbar Please create two new list of tests in your reply to the comment.

1. List of tests that are complete
1. List of pending tests

**Comment by SuhasHebbar** [comment]
List of complete Tests:
1. retrieving the given schedule
2. updating the station schedule
3. Receive a itinerary search query
4. Send completed search query to neighbours
5. Does not forward stale queries
6. Does not forward queries with self loops
7. Incorrectly received queries are discarded
8. No query is forwarded from a Station with no viable paths
9. The correct itinerary is forwarded to the next station
10. The correct itinerary is forwarded to the next station with the
11. Terminated queries are handed over to query collector with correct itinerary

Does not pass in travis build but seems to pass in local server
1. Consumes rapid stream of mixed input queries

**Comment by SuhasHebbar** [comment]
Presently to remove the MockStation module and use a mox mock instead one would have to pass the Station module as a dependency to the Station GenServer.
In the last discussion we did not reach a conclusion regarding that. Shall I go on forward with the existing infrastructure? That is ```[station_state, registry, collector, neighbour_station]```.

**Comment by prasadtalasila** [comment]
I remember agreeing to Station behaviour. If the station behaviour is specified, we can then rely on the guaranteed availability of function implementations in all the arguments passed to that function. So instead of a MockStation, please put in Station behaviour and pass a mocked version of that behaviour in ExUnit tests.

**Comment by SuhasHebbar** [comment]
There is a minor problem regarding the use of verify for testing.
The code given below will not pass the test case.
```elixir
Station.send_to_station(pid, itinerary)
verify!(MockStation)
```

But, the code given below will.
Station.send_to_station(pid, itinerary)
:timer.sleep(10)
verify!(MockStation)

This is because there is a race condition between the call of Mox.verify/1 and MockStation.sent_to_station/2.

In the test process right after the async call Station.sent_to_station/2 is made verify/2 is called, but at the Station the FSM has not reached MockStation.sent_to_station/2 hence the verification will fail.

Due to this I would suggest that rather than using verify! we stick to the previous methodology. Now the only change being MockStation being replaced with the mox mock MockStation.

**Comment by prasadtalasila** [comment]
@SuhasHebbar 

More tests for station module.

1. A station forwards a valid query to all the chosen neighbours who have an eligible connection.
1. A station forwards only one valid query to each neighbour (to make sure only one connection per neighour is utilized from the connection array).
1. A station considers connection array to be a circular array and comes back to the beginning of the array after reaching the end.
    1. Does this for one neighbour
    1. Does this for all the neighbours

Please add these new tests to the station tests module.

**Comment by SuhasHebbar** [comment]
For 
3. A station considers connection array to be a circular array and comes back to the beginning of the array after reaching the end.
   i.  Does this for one neighbour
  ii. Does this for all the neighbours

I have instead included a test to check if the station schedule remains unchanged after processing a query. This is because the points mentioned in the tests do not occur in the fsm implementation.

There is no index as such. A copy of the schedule is added to the fsm data from which the head is extracted in each compute_itinerary event. Hence the next time compute_itinerary is invoked the head will no longer be there in the schedule copy. This stops when the stop function becomes true or the end of the list is reached.

Throughout since we're operating on a copy of the schedule the actual station schedule remains unchanged. So on the next query again a copy of the schedule is made.

**Comment by prasadtalasila** [comment]
@SuhasHebbar 

Since we are not changing the schedule during itinerary search, do we need to make a copy of it?

### On the circular schedule
We do need to iterate over the schedule for one cycle to find the feasible connections to neighbours. It is better to think of the schedule as a circular array, representing the periodicity of transport facilities. The way to process the connection array would be to identify the starting index of the first eligible connection (i.e., the first connection whose start time is greater than the arrival time of the itinerary) and then process all the connections from that point on wards.

We stop based on two conditions:
1. One eligible connection has been picked for each neighbour.
1. All connections have been exhausted.

**Comment by SuhasHebbar** [comment]
The implementation of a list in elixir can be visualised as a linked list of pointers. Removing the head of a list is equivalent to pointing the list identifier (which is a reference to the list object) to the next element (or the head of the tail), hence we have guaranteed O(1) peformance. We do not construct the whole schedule list from scratch.

**Comment by SuhasHebbar** [comment]
I do not see the need to maintain an index as the method used to iterate over a list is more similar to list comprehension than anything. In every pass in compute itinerary it iterates over the remaining connections until it encounters a valid connection or reaches the end of the schedule list.

The index would only make sense in an array, which it is not.

If it has reached the end it has exhausted all possible connection and has reached the end of query processing at that station. Hence ending the block and making way for the next query to be processed.

**Comment by SuhasHebbar** [comment]
I do not see the need to maintain an index as the method used to iterate over a list is more similar to list comprehension than anything. In every pass in compute itinerary it iterates over the remaining connections until it encounters a valid connection or reaches the end of the schedule list.

The index would only make sense in an array, which it is not.

If it has reached the end it has exhausted all possible connection and has reached the end of query processing at that station. Hence ending the block and making way for the next query to be processed.

**Comment by prasadtalasila** [comment]
Work completed via PR #78.
