### ISSUE TITLE
build passing only on local server

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#54]
Build status of both master and ts-v2.0-alpha branches on the local server.

**Comment by SuhasHebbar** [comment]
The master build is passing as expected on the local server but one cannot use the API outside the local server.
curl -X GET 'http://10.1.9.175:8880/api/station/state?station_code=1' does not work on the server or any other system.

One only has access to the application functions on the server using localhost instead of 10.1.9.175.

**Comment by prasadtalasila** [comment]
Can we decipher the problem by looking into the API module?

**Comment by SuhasHebbar** [comment]
Yes, as maru should give us access to the application API even outside localhost.
I think @VedangW should be more familiar with the working of maru.

**Comment by prasadtalasila** [comment]
based on the suggestions available on [this question](https://elixirforum.com/t/how-to-bind-phoenix-app-to-specific-ip-address/1702/12), we need to add IP address to [maru config](https://github.com/prasadtalasila/TransportScheduler/blob/dev/config/config.exs#L33). The line should probably be like this:
```
http: [port: 5000, ip: {10,1,9,175}]
```

**Comment by VedangW** [comment]
@SuhasHebbar I'm not sure what the problem is, but I'm not being able to ssh in the server at the moment. Maybe its some mistake on my part. I'll try to look into it tomorrow.

**Comment by prasadtalasila** [comment]
Not a priority right now.
