### ISSUE TITLE
Improvements to station module

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/TransportScheduler#71]
The list of improvements to the station module coming via PR #66.

@SuhasHebbar Please add the list of changes / suggestions from your side.

**Comment by SuhasHebbar** [comment]
The improvements coming via PR #66. are as follows:
1. The Station will only choose one valid path for each neighbouring station, hence only one itinerary/message will be forwarded to each neighbouring station. This should help mitigate the "memory explosion" seen in the application (though how much exactly this will help has to be seen in stress tests and profiling).

2. Improved decoupling of dependencies from the Station module. One more advantage of incorporating the Station core functionality into gen_fsm is that since we have decoupled the core functionality from the Station interface, if we move away from the GenServer implementation one should not need any major refactoring to get the Station working again.

3. More comprehensive tests on the core functionality of the Station module.

**Comment by SuhasHebbar** [comment]
Work for future PRs:

1. The query/itinerary structure that was discussed ({query, preferences, itinerary, cost}). 

2. I think the Station Struct container can do with further optimisation (for both semantics and performance). I would also like to explore for a possible abstraction for the itinerary container so that we do not have to change the Station implementation again if we come upon a more efficient itinerary container.

3. It also would be good to pass the Station module along with the NetworkConstructor and the QueryCollector as dependencies. As without that we make the assumption that all neighbouring Stations use the same Station implementation (this fails during testing as we use MockStation, which would then lead to an implicit assumption that the neighbouring Stations are GenServers).

4. Stress tests on gen_fsm. gen_fsm helped us to arrange the station logic in a more easily compehensible manner but at the present we do not have an idea of the overhead it adds to the Station. So stress tests on gen_fsm vs pure GenServer Stations would be good.

**Comment by prasadtalasila** [comment]
@SuhasHebbar We agreed on a few refactoring suggestions yesterday. Please list the relevant advice to station module in this issue.

**Comment by prasadtalasila** [comment]
Work completed via PR #69
